name: Build & push docker image
on: [workflow_dispatch]

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v3
      - uses: docker/metadata-action@v3
        id: metadata
        with:
          images: rg.fr-par.scw.cloud/finotor/invoiceninja
          tags: |
            type=sha,prefix={{branch}}-
            type=semver,enable=true,pattern={{version}}
          flavor: latest=false
      - name: Login to Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.REGISTRY_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: ${{ github.event_name != 'pull_request' }}
          #executor: gcr.io/kaniko-project/executor:latest
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          context: .
          file: ./Dockerfile
          no-cache: true
